/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import static hangman.LinkyListo.curr;
import static hangman.LinkyListo.head;
import javax.swing.JOptionPane;

/**
 *
 * @author Samima
 */
public class PScreen extends javax.swing.JFrame {

    /**
     * Creates new form PScreen
     */
     MenuScreen obj; Hangman ob; String updatedWord; Trie2 tri;
    public PScreen() {
        initComponents();
    }
public PScreen(String p1, String p2, String p3, String p4) {
    initComponents();
    boolean nabeel = false;
    LinkyListo LOL = new LinkyListo();
       P1.setText(p1);
       S1.setText(LOL.findScore(p1, head) + "");
       //if (!p1.equals("")) LOL.insert(p1, 0);
       P2.setText(p2);
       S2.setText(LOL.findScore(p2, head) + "");
       //if (!p2.equals("")) LOL.insert(p2, 0);
       P3.setText(p3);
       S3.setText(LOL.findScore(p3, head) + "");
       //if (!p3.equals("")) LOL.insert(p3, 0);
       P4.setText(p4);
       S4.setText(LOL.findScore(p4, head) + "");
       //if (!p4.equals("")) LOL.insert(p4, 0);
      // LOL.Print();
       while (curr.name.equals(" "))
       {
           if (curr == head && nabeel) break;
           if (!nabeel) nabeel = true;
           curr = curr.next;
       }
       if (curr == head && nabeel){
           JOptionPane.showMessageDialog(rootPane, "No one is playing. Move back to the menu screen.");
           jButton1.setEnabled(false);
           //this.dispose();
           //new MenuScreen().setVisible(true);
       }
       P1name.setText(curr.name);
       System.out.println(curr.score);
      // tempLabel.setVisible(false);
       ob = new Hangman();
      // ob.userGuess();
       disWord.setText(ob.getDistinguishedWord());
       //jTextField1.setText(ob.getDistinguishedWord().charAt(0) + "");
        int len = ob.getSecretWord().length();
        jLabel11.setText("The first letter is given to you. The number of alphabets u have to guess to get the word are : " + (len - 1));
         updatedWord = ob.getSecretWord().charAt(0) +"";
         System.out.println("secret word: " + ob.getSecretWord());
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JLabel();
        S1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        S4 = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        P1name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        disWord = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        P1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        P1.setText("Player 1");
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        S1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        S1.setText("0");
        getContentPane().add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 10, -1));

        P2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        P2.setText("Player 2");
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        S2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        S2.setText("0");
        getContentPane().add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        P3.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        P3.setText("Player 3");
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        S3.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        S3.setText("0");
        getContentPane().add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, -1));

        P4.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        P4.setText("Player 4");
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, -1, -1));

        S4.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        S4.setText("0");
        getContentPane().add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, -1, -1));

        tempLabel.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        tempLabel.setText("\"\"");
        getContentPane().add(tempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        P1name.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        P1name.setText("Player Name");
        getContentPane().add(P1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel11.setText("The first letter is given to you.The number of alphabets you have to guess to get the word are : ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        jLabel12.setText("Guess the word, character by character, in order.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, 20));

        disWord.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        disWord.setText("UserGuess");
        getContentPane().add(disWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 400, -1));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 150, 40));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/menuscreen-01.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char ch = 0;
        try
        {
            ch = jTextField1.getText().charAt(0);
        }
        catch (StringIndexOutOfBoundsException e)
        {
            JOptionPane.showMessageDialog(rootPane, "Empty input is not acceptable.");
            //System.exit(0);
        }
        if (ch == 0) JOptionPane.showMessageDialog(rootPane, "Please enter a character.");
        else
        {
            jTextField1.setText("");
            jLabel12.setText("Guess the next character in order:");
            // int len = ob.getSecretWord().length();

            //  Scanner sc = new Scanner(System.in);

            updatedWord = updatedWord + java.lang.Character.toLowerCase(ch);
            disWord.setText(updatedWord);
            boolean doesMatch; String sw;
            if (updatedWord.length() == ob.getSecretWord().length()){

                doesMatch = ob.checkGuessedWord(updatedWord);
                if (doesMatch){
                    //this.hide();
                    Result cong = new Result("matched", ob.getSecretWord());
                    cong.setVisible(true);
                    this.dispose();}
                else{
                    //this.hide();
                    Result lose = new Result("not matched", ob.getSecretWord());
                    lose.setVisible(true);
                    this.dispose();}}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   this.setVisible(false);
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1name;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JLabel disWord;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
