/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import static hangman.LinkyListo.curr;
import static hangman.LinkyListo.head;

/**
 *
 * @author Samima
 */
public class ResultForLV2 extends javax.swing.JFrame {

    /**
     * Creates new form Congratulations
     */
    public ResultForLV2(String str, String originalWord) {
        initComponents();
        if (str.equals("matched")){
        resultSentence.setText("Congratulations! You have guessed the word correctly!");
        earned.setText(earned.getText() + "1 point");
        curr.score++;}
        else{
           resultSentence.setText("you have guessed it incorrectly. The word was " + originalWord);  
           earned.setText(earned.getText() + "0 points");}
    }
    
    public ResultForLV2(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resultSentence = new javax.swing.JLabel();
        earned = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 360, -1, -1));

        resultSentence.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        resultSentence.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultSentence.setText("Result sentence");
        getContentPane().add(resultSentence, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 710, 60));

        earned.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        earned.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        earned.setText("You have earned: ");
        getContentPane().add(earned, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 600, 50));

        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setText("Give turn to next player");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 270, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/menuscreen-01.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        
        curr = curr.next;
        System.out.println(curr.name);

        
       
          
        while(curr.name.equals(" "))
        {
            if (curr == head) break;          
                curr = curr.next;           
        }
      LinkyListo LOL = new LinkyListo();
        String[] arr = LOL.Players(head);
        if (curr == head) {
        WhoWon ww = new WhoWon(arr);
        ww.setVisible(true);// then end the game
         
        }
        else{
         new Second_Level(arr[0], arr[1], arr[2], arr[3]).setVisible(true);
        
        }
        this.setVisible(false); 
        
        
     
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultForLV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultForLV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultForLV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultForLV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultForLV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel earned;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel resultSentence;
    // End of variables declaration//GEN-END:variables
}
