/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import static hangman.LinkyListo.curr;
import static hangman.LinkyListo.head;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Second_Level extends javax.swing.JFrame {

    /**
     * Creates new form Second_Level
     */
    Trie2 T2 = new Trie2();
    boolean ENDCHECK = false;
    boolean nabeel = false;
    String disp = "";  
    int count = 0;
    String word4user = T2.randomWordPick();
    int x = word4user.length();
    char[] charARR = new char[x];
    boolean[] Kapil = new boolean[x];
    public Second_Level() {
        initComponents();
        go.setVisible(false);
    }
    public Second_Level(String p1, String p2, String p3, String p4)
    {
     //   go.setEnabled(false);
    initComponents();
    go.setEnabled(false);
    go.setVisible(false);
    LinkyListo LOL = new LinkyListo();
       P1.setText(p1);
       S1.setText("Score:" + LOL.findScore(p1, head) + "");
       //if (!p1.equals("")) LOL.insert(p1, 0);
       P2.setText(p2);
       S2.setText("Score:" + LOL.findScore(p2, head) + "");
       //if (!p2.equals("")) LOL.insert(p2, 0);
       P3.setText(p3);
       S3.setText("Score:" + LOL.findScore(p3, head) + "");
       //if (!p3.equals("")) LOL.insert(p3, 0);
       P4.setText(p4);
       S4.setText("Score:" + LOL.findScore(p4, head) + "");
       //if (!p4.equals("")) LOL.insert(p4, 0);
      // LOL.Print();
      P1name.setText(curr.name);
             while (curr.name.equals(" "))
       {
           if (curr == head && nabeel) break;
           if (!nabeel) nabeel = true;
           curr = curr.next;
       }
       if (curr == head && nabeel){
           JOptionPane.showMessageDialog(rootPane, "No one is playing. Move back to the menu screen.");
           init.setEnabled(false);
           //this.dispose();
           //new MenuScreen().setVisible(true);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guess = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        go = new javax.swing.JButton();
        user_sees_this_label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        len = new javax.swing.JLabel();
        init = new javax.swing.JButton();
        P1 = new javax.swing.JLabel();
        S1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        S4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        P1name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessActionPerformed(evt);
            }
        });
        getContentPane().add(guess, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 143, -1));
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 143, -1));

        jLabel1.setText("Enter the character that you want to add:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 770, -1));

        jLabel2.setText("Enter the position for the character mentioned:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 770, -1));

        go.setText("Register input?");
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        user_sees_this_label.setText("The word is :");
        getContentPane().add(user_sees_this_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 789, 121));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 127, -1));

        len.setText("The length of the word: ");
        getContentPane().add(len, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 157, 22));

        init.setText("Initialize");
        init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initActionPerformed(evt);
            }
        });
        getContentPane().add(init, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        P1.setText("P1");
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 73, -1));

        S1.setText("Score: ");
        getContentPane().add(S1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 73, -1));

        P2.setText("P2");
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 95, -1));

        S2.setText("Score:");
        getContentPane().add(S2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 484, -1));

        P3.setText("P3");
        getContentPane().add(P3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 86, -1));

        S3.setText("Score:");
        getContentPane().add(S3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 78, -1));

        P4.setText("P4");
        getContentPane().add(P4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 83, -1));

        S4.setText("Score:");
        getContentPane().add(S4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 75, -1));

        jLabel3.setText("Currently playing:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 23));

        P1name.setText("jLabel4");
        getContentPane().add(P1name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 127, 23));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/menuscreen-01.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 950, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
        //len.setText(x + "");
        //user_sees_this_label.setText("The word is: " + word4user.charAt(0));
        System.out.println(word4user);
        System.out.println(Kapil[0]);
        char guessW = guess.getText().charAt(0);
        int pos = Integer.parseInt(position.getText());
        if (pos >= x || pos < 0) JOptionPane.showMessageDialog(rootPane, "Invalid index for character placement, please try again.");
        else
        {
            
            if (Kapil[pos] != true)
                {
                charARR[pos] = guessW;
                Kapil[pos] = true;
                System.out.println(charARR[pos]);
                JOptionPane.showMessageDialog(rootPane, "Entered character: " + guessW + " at position: " + pos);
                }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "That place has already been filled, try some other place.");
            }
                for (int i = 0; i < charARR.length; i++) 
                {
                    if (Kapil[i] == false) 
                    {
                        charARR[i] = '_';
                    }
                    disp = disp + charARR[i] + " ";
                }
            System.out.println(disp);
            user_sees_this_label.setText("The word you have assembled thus far: " + disp);
        }
        for (int i = 0; i < Kapil.length; i++) 
        {
            if (Kapil[i] == true) count++;
        }
        if (count == word4user.length())
        {
            JOptionPane.showMessageDialog(rootPane, "All the placements have been made.");
            disp = disp.replaceAll(" ", "");
            if (disp.equalsIgnoreCase(word4user))
            {
                //JOptionPane.showMessageDialog(rootPane, "Congratulations! Your placement was on spot!");
                //this.dispose();
                //new MainScreen().setVisible(true);
//                new ResultForLV2("matched", "").setVisible(true);
                new WhoWon();
                this.dispose();
                
                //curr.score++;
                //curr = curr.next;
                if (curr == head) ENDCHECK = true;
            }
            else
            {
                //JOptionPane.showMessageDialog(rootPane, "Sadly, the word you assembled does not match the actual word. The actual word was " + word4user);
                //this.dispose();
                //new MainScreen().setVisible(true);
                new ResultForLV2("not matched", word4user).setVisible(true);
                this.dispose();
                //curr.score++;
                //curr = curr.next;
                if (curr == head) ENDCHECK = true;
            }
        }
        else count = 0;
        disp = "";
        if (ENDCHECK = true)
        {
            LinkyListo LOL = new LinkyListo();
            //int max = LOL.Winner(head);
        }
        //boolean array
        //one try for every i
        
    }//GEN-LAST:event_goActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainScreen().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initActionPerformed
        // TODO add your handling code here:
        init.setVisible(false);
        user_sees_this_label.setText("The first letter of the word is: " + word4user.charAt(0));
        len.setText("The length of the word: " + x);
        go.setVisible(true);
        go.setEnabled(true);
    }//GEN-LAST:event_initActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_Level.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_Level().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1name;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JButton go;
    private javax.swing.JTextField guess;
    private javax.swing.JButton init;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel len;
    private javax.swing.JTextField position;
    private javax.swing.JLabel user_sees_this_label;
    // End of variables declaration//GEN-END:variables
}
