/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

/**
 *
 * @author Samima
 */
import static hangman.LinkyListo.head;
public class WhoWon extends javax.swing.JFrame {

    /**
     * Creates new form WhoWon
     */
     int count = 0;
    public WhoWon() {
        initComponents();
    }
 public WhoWon(String[] arr) {
        initComponents();
        LinkyListo ll = new LinkyListo();
      
        // more code needed for determining winner, and setting text of labels for this screen accordingly
      
      String playersWithOnePoint = "";
        for (int i = 0; i < arr.length; i++ ){
        if (ll.findScore(arr[i], head) == 1)  {
            count++;
            playersWithOnePoint = playersWithOnePoint + " " + arr[i];
        }  
        
        }
         if (count == 1){
             winOrDrawLabel.setText("The winner is:");
         jButton1.setText("Return to main page");
        }
         else{
             winOrDrawLabel.setText("It's a draw!");
          jButton1.setText("Return to main page");
         
         }
         playerNamesLabel.setText(playersWithOnePoint);
         
           p1.setText(arr[0] + " " + ll.findScore(arr[0], head) );
           p2.setText(arr[1]+ " " + ll.findScore(arr[1], head));
           p3.setText(arr[2]+ " " + ll.findScore(arr[2], head));
           p4.setText(arr[3]+ " " + ll.findScore(arr[3], head));
        
             }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        winOrDrawLabel = new javax.swing.JLabel();
        playerNamesLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setText("jLabel1");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        p2.setText("jLabel2");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        p3.setText("jLabel3");
        getContentPane().add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        p4.setText("jLabel4");
        getContentPane().add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        winOrDrawLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        winOrDrawLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winOrDrawLabel.setText("winner/draw");
        getContentPane().add(winOrDrawLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 474, -1));

        playerNamesLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        playerNamesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerNamesLabel.setText("Player name(s)");
        getContentPane().add(playerNamesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 270, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 351, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/menuscreen-01.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 940, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainScreen ms;
        if (count==1 || count == 0){
             ms = new MainScreen();
        ms.setVisible(true);
        this.setVisible(false);}
        
        else {
           // go to second level 
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WhoWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WhoWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WhoWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WhoWon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WhoWon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel playerNamesLabel;
    private javax.swing.JLabel winOrDrawLabel;
    // End of variables declaration//GEN-END:variables
}
