/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

/**
 *
 * @author Samima
 */
public class PScreen extends javax.swing.JFrame {

    /**
     * Creates new form PScreen
     */
     MenuScreen obj; Hangman ob; String updatedWord; Trie2 tri;
    public PScreen() {
        initComponents();
    }
public PScreen(String p1, String p2, String p3, String p4) {
    initComponents();
       P1.setText(p1);
       P2.setText(p2);
       P3.setText(p3);
       P4.setText(p4);
       P1name.setText(p1);
       ob = new Hangman();
      // ob.userGuess();
       disWord.setText(ob.getDistinguishedWord());
       //jTextField1.setText(ob.getDistinguishedWord().charAt(0) + "");
        int len = ob.getSecretWord().length();
        jLabel11.setText("The first letter is given to you.The number of alphabets u have to guessed to get the word are : " + (len - 1));
         updatedWord = ob.getSecretWord().charAt(0) +"";
         tempLabel.setText(tempLabel.getText() + ob.getSecretWord());
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        P1name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        disWord = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        P1.setText("jLabel1");

        jLabel2.setText("0");

        P2.setText("jLabel3");

        jLabel4.setText("0");

        P3.setText("jLabel5");

        jLabel6.setText("0");

        P4.setText("jLabel7");

        jLabel8.setText("0");

        tempLabel.setText("secret word:");

        P1name.setText("Player 1 name");

        jLabel11.setText("The first letter is given to you.The number of alphabets u have to guessed to get the word are : ");

        jLabel12.setText("Guess the word, character by character, in order.");

        disWord.setText("disWord");

        jLabel14.setText(".");

        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tempLabel)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(P1)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(45, 45, 45)
                                .addComponent(P2)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(P3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(P1name)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(34, 34, 34)
                                        .addComponent(P4)))))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(disWord)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel14)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1)
                    .addComponent(jLabel2)
                    .addComponent(P2)
                    .addComponent(jLabel4)
                    .addComponent(P3)
                    .addComponent(jLabel6)
                    .addComponent(P4)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37)
                .addComponent(tempLabel)
                .addGap(39, 39, 39)
                .addComponent(P1name)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addComponent(disWord)
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char ch = jTextField1.getText().charAt(0);
        jTextField1.setText("");
        jLabel14.setText("Guess the next character in order:");
     // int len = ob.getSecretWord().length();
       
      //  Scanner sc = new Scanner(System.in);
      
            
            
            updatedWord = updatedWord + java.lang.Character.toLowerCase(ch);
            disWord.setText(updatedWord);
           boolean doesMatch; String sw;
        if (updatedWord.length() == ob.getSecretWord().length()){
                                                   
         doesMatch = ob.checkGuessedWord( updatedWord);
         if (doesMatch){
             this.hide();
         Result cong = new Result("matched", ob.getSecretWord());
         cong.setVisible(true);}
         else{
         this.hide();
         Result lose = new Result("not matched", ob.getSecretWord());
         lose.setVisible(true);}}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1name;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel disWord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
