/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import static hangman.LinkyListo.curr;
import static hangman.LinkyListo.head;
import javax.swing.JOptionPane;

/**
 *
 * @author Samima
 */
public class PScreen extends javax.swing.JFrame {

    /**
     * Creates new form PScreen
     */
     MenuScreen obj; Hangman ob; String updatedWord; Trie2 tri;
    public PScreen() {
        initComponents();
    }
public PScreen(String p1, String p2, String p3, String p4) {
    initComponents();
    LinkyListo LOL = new LinkyListo();
       P1.setText(p1);
       S1.setText(LOL.findScore(p1, head) + "");
       //if (!p1.equals("")) LOL.insert(p1, 0);
       P2.setText(p2);
       S2.setText(LOL.findScore(p2, head) + "");
       //if (!p2.equals("")) LOL.insert(p2, 0);
       P3.setText(p3);
       S3.setText(LOL.findScore(p3, head) + "");
       //if (!p3.equals("")) LOL.insert(p3, 0);
       P4.setText(p4);
       S4.setText(LOL.findScore(p4, head) + "");
       //if (!p4.equals("")) LOL.insert(p4, 0);
      // LOL.Print();
       P1name.setText(curr.name);
       System.out.println(curr.score);
      // tempLabel.setVisible(false);
       ob = new Hangman();
      // ob.userGuess();
       disWord.setText(ob.getDistinguishedWord());
       //jTextField1.setText(ob.getDistinguishedWord().charAt(0) + "");
        int len = ob.getSecretWord().length();
        jLabel11.setText("The first letter is given to you. The number of alphabets u have to guess to get the word are : " + (len - 1));
         updatedWord = ob.getSecretWord().charAt(0) +"";
         tempLabel.setText(tempLabel.getText() + ob.getSecretWord());
    
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        P1 = new javax.swing.JLabel();
        S1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        S2 = new javax.swing.JLabel();
        P3 = new javax.swing.JLabel();
        S3 = new javax.swing.JLabel();
        P4 = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        P1name = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        disWord = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        S4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        P1.setText("jLabel1");

        S1.setText("0");

        P2.setText("jLabel3");

        S2.setText("0");

        P3.setText("jLabel5");

        S3.setText("0");

        P4.setText("jLabel7");

        tempLabel.setText("secret word:");

        P1name.setText("Player 1 name");

        jLabel11.setText("The first letter is given to you.The number of alphabets u have to guessed to get the word are : ");

        jLabel12.setText("Guess the word, character by character, in order.");

        disWord.setText("disWord");

        jLabel14.setText(".");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        S4.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(P1)
                        .addGap(28, 28, 28)
                        .addComponent(S1)
                        .addGap(45, 45, 45)
                        .addComponent(P2)
                        .addGap(29, 29, 29)
                        .addComponent(S2)
                        .addGap(30, 30, 30)
                        .addComponent(P3)
                        .addGap(18, 18, 18)
                        .addComponent(S3)
                        .addGap(34, 34, 34)
                        .addComponent(P4)
                        .addGap(33, 33, 33)
                        .addComponent(S4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(tempLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(P1name))
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(disWord))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(392, 392, 392)
                        .addComponent(jButton1)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1)
                    .addComponent(S1)
                    .addComponent(P2)
                    .addComponent(S2)
                    .addComponent(P3)
                    .addComponent(S3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(P4)
                        .addComponent(S4)))
                .addGap(37, 37, 37)
                .addComponent(tempLabel)
                .addGap(39, 39, 39)
                .addComponent(P1name)
                .addGap(36, 36, 36)
                .addComponent(jLabel11)
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addComponent(disWord)
                .addGap(8, 8, 8)
                .addComponent(jLabel14)
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char ch = 0;
               try
               {
                   ch = jTextField1.getText().charAt(0);
               }
               catch (StringIndexOutOfBoundsException e)
               {
                   JOptionPane.showMessageDialog(rootPane, "Empty input is not acceptable.");
                   //System.exit(0);
               }
        if (ch == 0) JOptionPane.showMessageDialog(rootPane, "Please enter a character.");
        else
        {
        jTextField1.setText("");
        jLabel14.setText("Guess the next character in order:");
     // int len = ob.getSecretWord().length();
       
      //  Scanner sc = new Scanner(System.in);
      
            
            
            updatedWord = updatedWord + java.lang.Character.toLowerCase(ch);
            disWord.setText(updatedWord);
           boolean doesMatch; String sw;
        if (updatedWord.length() == ob.getSecretWord().length()){
                                                   
         doesMatch = ob.checkGuessedWord( updatedWord);
         if (doesMatch){
             //this.hide();
         Result cong = new Result("matched", ob.getSecretWord());
         cong.setVisible(true);
         this.dispose();}
         else{
         //this.hide();
         Result lose = new Result("not matched", ob.getSecretWord());
         lose.setVisible(true);
         this.dispose();}}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P1name;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel P3;
    private javax.swing.JLabel P4;
    private javax.swing.JLabel S1;
    private javax.swing.JLabel S2;
    private javax.swing.JLabel S3;
    private javax.swing.JLabel S4;
    private javax.swing.JLabel disWord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tempLabel;
    // End of variables declaration//GEN-END:variables
}
